/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/alias-rahil/cluster-configs/pkg/apis/clusterconfigs.io/v1alpha1"
	scheme "github.com/alias-rahil/cluster-configs/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterSecretsGetter has a method to return a ClusterSecretInterface.
// A group's client should implement this interface.
type ClusterSecretsGetter interface {
	ClusterSecrets(namespace string) ClusterSecretInterface
}

// ClusterSecretInterface has methods to work with ClusterSecret resources.
type ClusterSecretInterface interface {
	Create(ctx context.Context, clusterSecret *v1alpha1.ClusterSecret, opts v1.CreateOptions) (*v1alpha1.ClusterSecret, error)
	Update(ctx context.Context, clusterSecret *v1alpha1.ClusterSecret, opts v1.UpdateOptions) (*v1alpha1.ClusterSecret, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterSecret, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterSecretList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterSecret, err error)
	ClusterSecretExpansion
}

// clusterSecrets implements ClusterSecretInterface
type clusterSecrets struct {
	client rest.Interface
	ns     string
}

// newClusterSecrets returns a ClusterSecrets
func newClusterSecrets(c *ClusterconfigsV1alpha1Client, namespace string) *clusterSecrets {
	return &clusterSecrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterSecret, and returns the corresponding clusterSecret object, and an error if there is any.
func (c *clusterSecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterSecret, err error) {
	result = &v1alpha1.ClusterSecret{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustersecrets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterSecrets that match those selectors.
func (c *clusterSecrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterSecretList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterSecretList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustersecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterSecrets.
func (c *clusterSecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clustersecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterSecret and creates it.  Returns the server's representation of the clusterSecret, and an error, if there is any.
func (c *clusterSecrets) Create(ctx context.Context, clusterSecret *v1alpha1.ClusterSecret, opts v1.CreateOptions) (result *v1alpha1.ClusterSecret, err error) {
	result = &v1alpha1.ClusterSecret{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clustersecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterSecret).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterSecret and updates it. Returns the server's representation of the clusterSecret, and an error, if there is any.
func (c *clusterSecrets) Update(ctx context.Context, clusterSecret *v1alpha1.ClusterSecret, opts v1.UpdateOptions) (result *v1alpha1.ClusterSecret, err error) {
	result = &v1alpha1.ClusterSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustersecrets").
		Name(clusterSecret.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterSecret).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterSecret and deletes it. Returns an error if one occurs.
func (c *clusterSecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustersecrets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterSecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustersecrets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterSecret.
func (c *clusterSecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterSecret, err error) {
	result = &v1alpha1.ClusterSecret{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clustersecrets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
