/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/alias-rahil/cluster-configs/pkg/apis/clusterconfigs.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterConfigMaps implements ClusterConfigMapInterface
type FakeClusterConfigMaps struct {
	Fake *FakeClusterconfigsV1alpha1
	ns   string
}

var clusterconfigmapsResource = schema.GroupVersionResource{Group: "clusterconfigs.io", Version: "v1alpha1", Resource: "clusterconfigmaps"}

var clusterconfigmapsKind = schema.GroupVersionKind{Group: "clusterconfigs.io", Version: "v1alpha1", Kind: "ClusterConfigMap"}

// Get takes name of the clusterConfigMap, and returns the corresponding clusterConfigMap object, and an error if there is any.
func (c *FakeClusterConfigMaps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterConfigMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterconfigmapsResource, c.ns, name), &v1alpha1.ClusterConfigMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterConfigMap), err
}

// List takes label and field selectors, and returns the list of ClusterConfigMaps that match those selectors.
func (c *FakeClusterConfigMaps) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterConfigMapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterconfigmapsResource, clusterconfigmapsKind, c.ns, opts), &v1alpha1.ClusterConfigMapList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterConfigMapList{ListMeta: obj.(*v1alpha1.ClusterConfigMapList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterConfigMapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterConfigMaps.
func (c *FakeClusterConfigMaps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterconfigmapsResource, c.ns, opts))

}

// Create takes the representation of a clusterConfigMap and creates it.  Returns the server's representation of the clusterConfigMap, and an error, if there is any.
func (c *FakeClusterConfigMaps) Create(ctx context.Context, clusterConfigMap *v1alpha1.ClusterConfigMap, opts v1.CreateOptions) (result *v1alpha1.ClusterConfigMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterconfigmapsResource, c.ns, clusterConfigMap), &v1alpha1.ClusterConfigMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterConfigMap), err
}

// Update takes the representation of a clusterConfigMap and updates it. Returns the server's representation of the clusterConfigMap, and an error, if there is any.
func (c *FakeClusterConfigMaps) Update(ctx context.Context, clusterConfigMap *v1alpha1.ClusterConfigMap, opts v1.UpdateOptions) (result *v1alpha1.ClusterConfigMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterconfigmapsResource, c.ns, clusterConfigMap), &v1alpha1.ClusterConfigMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterConfigMap), err
}

// Delete takes name of the clusterConfigMap and deletes it. Returns an error if one occurs.
func (c *FakeClusterConfigMaps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clusterconfigmapsResource, c.ns, name, opts), &v1alpha1.ClusterConfigMap{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterConfigMaps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterconfigmapsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterConfigMapList{})
	return err
}

// Patch applies the patch and returns the patched clusterConfigMap.
func (c *FakeClusterConfigMaps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterConfigMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterconfigmapsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterConfigMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterConfigMap), err
}
