/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/alias-rahil/cluster-configs/pkg/apis/clusterconfigs.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterSecrets implements ClusterSecretInterface
type FakeClusterSecrets struct {
	Fake *FakeClusterconfigsV1alpha1
	ns   string
}

var clustersecretsResource = schema.GroupVersionResource{Group: "clusterconfigs.io", Version: "v1alpha1", Resource: "clustersecrets"}

var clustersecretsKind = schema.GroupVersionKind{Group: "clusterconfigs.io", Version: "v1alpha1", Kind: "ClusterSecret"}

// Get takes name of the clusterSecret, and returns the corresponding clusterSecret object, and an error if there is any.
func (c *FakeClusterSecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clustersecretsResource, c.ns, name), &v1alpha1.ClusterSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSecret), err
}

// List takes label and field selectors, and returns the list of ClusterSecrets that match those selectors.
func (c *FakeClusterSecrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterSecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clustersecretsResource, clustersecretsKind, c.ns, opts), &v1alpha1.ClusterSecretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterSecretList{ListMeta: obj.(*v1alpha1.ClusterSecretList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterSecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterSecrets.
func (c *FakeClusterSecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clustersecretsResource, c.ns, opts))

}

// Create takes the representation of a clusterSecret and creates it.  Returns the server's representation of the clusterSecret, and an error, if there is any.
func (c *FakeClusterSecrets) Create(ctx context.Context, clusterSecret *v1alpha1.ClusterSecret, opts v1.CreateOptions) (result *v1alpha1.ClusterSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clustersecretsResource, c.ns, clusterSecret), &v1alpha1.ClusterSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSecret), err
}

// Update takes the representation of a clusterSecret and updates it. Returns the server's representation of the clusterSecret, and an error, if there is any.
func (c *FakeClusterSecrets) Update(ctx context.Context, clusterSecret *v1alpha1.ClusterSecret, opts v1.UpdateOptions) (result *v1alpha1.ClusterSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clustersecretsResource, c.ns, clusterSecret), &v1alpha1.ClusterSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSecret), err
}

// Delete takes name of the clusterSecret and deletes it. Returns an error if one occurs.
func (c *FakeClusterSecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clustersecretsResource, c.ns, name, opts), &v1alpha1.ClusterSecret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterSecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clustersecretsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterSecretList{})
	return err
}

// Patch applies the patch and returns the patched clusterSecret.
func (c *FakeClusterSecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clustersecretsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSecret), err
}
